In [ ]:
#Scaling Techqniue
''' 
Scaling---->we use scaling  for scale the values into similler scale values .
 ------>Scaling useually do after spliting train and test data because from train data model should be learn and from test data it should predict
             the data.

             Train data= we use fit_transform()
             Test data=we use just tranform()-->if we use again fit here again fit predict again the new data that value that transform again.
 

---->when we use distance formula  distance has long values with compare to other values we do scaling to get into the same range 

1)StandardScaler
2)MinMaxScaler
3)RobustScaler

'''

In [17]:
#1)Min-Max Scaler - we get values with in the range of 0-1
'''  
Min-Max Scaler transforms the data so that all values lie between 0 and 1 (default range).
we use min val  and max val in column


            formula :  X(scale)= x-min_val/max_val-min_val

            Xscaled​=X-Xmin/Xmax​−Xmin


'''
import pandas as pd
import numpy as np
n_rows=15
data={
    "Age":np.random.randint(5,100,n_rows)
}
df=pd.DataFrame(data)
df


#scaling
from sklearn.preprocessing import MinMaxScaler

#creating obj before this we need to split the data for real time project but it just example I am not using train_test_split()
mms=MinMaxScaler()
df["Age_scaled"]=mms.fit_transform(df[["Age"]])
df

    Age  Age_scaled
0    84    0.843373
1    81    0.807229
2    75    0.734940
3    73    0.710843
4    58    0.530120
5    32    0.216867
6    76    0.746988
7    43    0.349398
8    97    1.000000
9    14    0.000000
10   59    0.542169
11   69    0.662651
12   25    0.132530
13   22    0.096386
14   53    0.469880

In [25]:
#2. Standard Scaler:Instead of range like 0-1 it uses mean and standard deviation
'''

            Z=X−μ/σ​
Where

X = Original value
μ = Mean
σ = Standard deviation

            
'''
from sklearn.preprocessing import StandardScaler

ss=StandardScaler()
df["Age_scaled_StandardScaler"]=ss.fit_transform(df[["Age"]])
df

    Age  Age_scaled  Age_scaled_StandardScaler
0    84    0.843373                   1.090335
1    81    0.807229                   0.967365
2    75    0.734940                   0.721425
3    73    0.710843                   0.639445
4    58    0.530120                   0.024594
5    32    0.216867                  -1.041147
6    76    0.746988                   0.762415
7    43    0.349398                  -0.590256
8    97    1.000000                   1.623205
9    14    0.000000                  -1.778967
10   59    0.542169                   0.065584
11   69    0.662651                   0.475484
12   25    0.132530                  -1.328077
13   22    0.096386                  -1.451047
14   53    0.469880                  -0.180356

In [31]:
# Robust Scaler
'''  
3. Robust Scaler

Robust Scaler uses:

Median
Interquartile Range (IQR)

instead of mean and standard deviation.

Since median is not affected much by extreme values, Robust Scaler handles outliers better.

'''

from sklearn.preprocessing import RobustScaler

#object creation

rs=RobustScaler()

df["Age_scaled_RobustScaler"]=rs.fit_transform(df[["Age"]])
df

    Age  Age_scaled  Age_scaled_StandardScaler  Age_scaled_RobustScaler
0    84    0.843373                   1.090335                 0.657895
1    81    0.807229                   0.967365                 0.578947
2    75    0.734940                   0.721425                 0.421053
3    73    0.710843                   0.639445                 0.368421
4    58    0.530120                   0.024594                -0.026316
5    32    0.216867                  -1.041147                -0.710526
6    76    0.746988                   0.762415                 0.447368
7    43    0.349398                  -0.590256                -0.421053
8    97    1.000000                   1.623205                 1.000000
9    14    0.000000                  -1.778967                -1.184211
10   59    0.542169                   0.065584                 0.000000
11   69    0.662651                   0.475484                 0.263158
12   25    0.132530                  -1.328077                -0.894737
13   22    0.096386                  -1.451047                -0.973684
14   53    0.469880                  -0.180356                -0.157895